CREATE TABLE Towns(
Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
[Name] NVARCHAR(50) NOT NULL
)


CREATE TABLE Addresses(
Id INT PRIMARY KEY IDENTITY NOT NULL,
AddressText NVARCHAR(50) NOT NULL,
TownId INT NOT NULL,
FOREIGN KEY (TownId) REFERENCES Towns(Id)
)



--	Departments (Id, Name)
CREATE TABLE Departments(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] NVARCHAR(50) NOT NULL
)


CREATE TABLE Employees (
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName NVARCHAR(50) NOT NULL,
MiddleName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
JobTitle NVARCHAR(50) NOT NULL,
DepartmentId INT NOT NULL,
FOREIGN KEY (DepartmentId) REFERENCES Departments(Id),
HireDate DATE,
Salary DECIMAL(15,2),
AddressId INT,
FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
)
